SELECT * FROM user WHERE
    username = "natas18" AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$ AND
    password REGEXP ^a.*$
